[[code]]
lang = "C / C++"
label = "jj1lis/gomamayo"
url = "https://github.com/jj1lis/gomamayo"

[[code]]
lang = "JavaScript / TypeScript"
label = "na2na-p/gomamayo-deno"
desc = "Denoで動作するゴママヨ検出ライブラリ"
url = "https://github.com/na2na-p/gomamayo-deno"

[[code]]
lang = "JavaScript / TypeScript"
label = "ThinaticSystem/gomamayo.js"
desc = "Node.jsで動作するしなちくシステム製のライブラリ"
url = "https://github.com/ThinaticSystem/gomamayo.js"

[[code]]
lang = "Golang"
label = "jugesuke/gomamayo"
url = "https://github.com/jugesuke/gomamayo"

[[code]]
lang = "Golang"
label = "yulog/go-gomamayo"
url = "https://github.com/yulog/go-gomamayo"

[[code]]
lang = "Python"
label = "AkaakuHub/gomamayo"
url = "https://github.com/AkaakuHub/gomamayo"

[[code]]
lang = "Python"
label = "mitei1720/discordbot/libs/gomi_util.py"
desc = "DiscordのBotとして実装されているゴママヨ"
url = "https://github.com/mitei1720/discordbot/blob/6c957d489da6970b8264e049a79adefed7c9698d/libs/goma_util.py#L13"

[[code]]
lang = "Scala"
label = "windymelt/gomamayo4s"
url = "https://github.com/windymelt/gomamayo4s"

[[code]]
lang = "Rust"
label = "statiolake/gomamayo-rs"
url = "https://github.com/statiolake/gomamayo-rs"

[[code]]
lang = "その他"
label = "AtCoder OUPC 2023 Day1 B Gomamayo"
url = "https://atcoder.jp/contests/oupc2023-day1/submissions?f.LanguageName=&f.Status=AC&f.Task=oupc2023_day1_b&f.User=&page=1"
desc = "一次多項ゴママヨの検出を行う\nRustやJava, Swift, PHP等で記述されたものもある"

[[websites]]
title = "ゴママヨ\\-用語集 \\| しなちくシステム"
url = "https://thinaticsystem.com/glossary/gomamayo"

[[websites]]
title = "【論説】ゴママヨおよびそれに付随するさまざまな現象の研究 - 0と1の間でティータイム"
url = "https://3qua9la-notebook.hatenablog.com/entry/2021/04/10/220317"

[[websites]]
title = "OUPC 2023 Day1 : 大阪大学セット B Gomamayo"
url = "https://atcoder.jp/contests/oupc2023-day1/tasks/oupc2023_day1_b"
